<a href="https://colab.research.google.com/github/YashDewan/BasicDataSc/blob/main/Numpy/Numpy_excercise_Assign_sol.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Import numpy as np**

In [ ]:
import numpy as np

**Create an array of 10 zeros**

In [ ]:
arr = np.zeros(10,dtype=np.int32)

In [ ]:
arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

**Create an array of 10 ones**

In [ ]:
arr = np.ones(10)

In [ ]:
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

**Create an array of 10 fives**

In [ ]:
arr = np.array([5]*10)

In [ ]:
arr

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

**Create an array of the integers from 10 to 50**

New 

In [ ]:
arr = np.arange(10,51)

In [ ]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

**Create an array of all the even integers from 10 to 50**

In [ ]:
arr = np.arange(10,51,2)

In [ ]:
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Create a 3x4 matrix with numbers ranging from 0 to 12**

In [ ]:
arr2 = np.arange(0,12)

In [ ]:
arr2.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Create a 3x3 identity matrix**

In [ ]:
arr = np.identity(3,dtype=np.int32)

In [ ]:
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

**Use Numpy to generate a random number between 0 and 1**

Note: output may differ from yours output

In [ ]:
randno = np.random.randint(0,2)
randno

0

**Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution**

Note: output may differ from yours output

In [ ]:
randno = np.random.randn(25)
randno

array([-5.35120769e-02,  6.70056520e-02, -9.90587257e-02, -1.13827381e+00,
        2.28995446e+00, -4.98726609e-01,  9.05369951e-01,  9.71696846e-01,
        7.74660468e-02,  6.10466518e-02, -5.20971413e-01, -1.06059487e+00,
       -5.81228361e-01, -2.15918663e-01, -4.08918067e-05, -3.86214159e-01,
        1.11747903e-01, -1.43796067e-01, -3.78983021e-01, -1.67745423e-01,
       -1.60055624e-01,  1.25789155e+00,  3.25989986e-01, -3.95578138e-01,
       -1.46669608e+00])

**Create an (10x10)array having numbers from 0.01 to 1 increasing by 0.01**

In [ ]:
arr = np.arange(0.01,1.01,0.01)
arr

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

#Numpy Indexing and Slicing


In [ ]:
ar = (np.arange(25)+1).reshape(5,5)
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

**extract array**

[
  [12,13,14],

  [17,18,19],

  [22,23,24]
]

In [ ]:
arr = ar[2:,1:4]

In [ ]:
arr

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

**extract array**

[
  [14, 13, 12],

  [19, 18, 17],

  [24, 23, 22]
]

In [ ]:
arr = ar[2: , 3:0:-1]

In [ ]:
arr

array([[14, 13, 12],
       [19, 18, 17],
       [24, 23, 22]])

**extract array**

[
  [24, 23, 22],

  [19, 18, 17],

  [14, 13, 12],  
]

In [ ]:
arr = ar[:1:-1 , 3:0:-1]

In [ ]:
arr

array([[24, 23, 22],
       [19, 18, 17],
       [14, 13, 12]])

#Split Concatinate

In [ ]:
ar = np.arange(2,10)
ar

array([2, 3, 4, 5, 6, 7, 8, 9])

**Split array to generate 3 arrays with content**

[2,3,4]

[5, 6]

[]

[7,8,9]

In [ ]:
arr = ar[0:3]
arr2 = ar[3:5]
arr3 = ar[1:1]
arr4 = ar[5:]

In [ ]:
arr,arr2,arr3,arr4

(array([2, 3, 4]), array([5, 6]), array([], dtype=int64), array([7, 8, 9]))

**2D**

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9]
])

**Concatinate array to create new array with content**

[
  [1,2,3],

  [4,5,6],
  
  [7,8,9]
]

In [ ]:
arr = np.concatenate((a,b))

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.array([
              [1,2,3],
              [4,5,6]
])
b = np.array([
              [7,8,9, 10],
              [11, 12, 13, 14]
])

**Concatinate array to create new array with content**

[

  [1,2,3, 7,8,9, 10],

  [4,5,6, 11, 12, 13, 14]
  
]

In [ ]:
arr = np.concatenate((a,b),axis=1)

In [ ]:
arr

array([[ 1,  2,  3,  7,  8,  9, 10],
       [ 4,  5,  6, 11, 12, 13, 14]])

#Broadcasting and Indexing

below array is created using random values so your output may differ. 

In [ ]:
ar = np.round(np.random.rand(10)*10)
ar

array([ 9.,  2.,  8.,  1.,  4.,  3., 10.,  8.,  3.,  7.])

**create new array containing all numbers which are smaller than 10 in ar**

In [ ]:
arr = np.where(ar<10)
arr

(array([0, 1, 2, 3, 4, 5, 7, 8, 9]),)

**create new array containing all numbers which are in range [3, 11] in ar**

In [ ]:
arr = np.where((ar>3) & (ar<=11))
arr

(array([0, 2, 4, 6, 7, 9]),)

**count how many numbers are minimum in ar**

1.   List item
2.   List item



example for arr = [2, 4, 6, 2, 9, 2]

min is 2

there are 3 occurences of 2

In [ ]:
arr = np.round(np.random.rand(10)*10)
arr

array([2., 9., 7., 4., 4., 8., 7., 8., 6., 3.])

In [ ]:
# word = arr.min()
# print(np.word.count(arr))

**Create an array of length 20 with first 15 numbers equal to 2 and last 5 numbers = -5**

In [ ]:
arr = np.array(([2]*15) + ([-5]*5))
arr

array([ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, -5, -5,
       -5, -5, -5])

**Sum min max of all elements of matrix**

In [ ]:
mat = np.array(
    [[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]]
)
mat

array([[57., 33., 44., 36., 11., 75., 51., 22., 86., 13.],
       [51., 16., 30., 92., 66., 54., 73.,  2., 25., 12.],
       [68., 14., 90., 27., 44., 54., 26., 61.,  1.,  3.],
       [86., 82., 10., 76., 12.,  1., 15., 89., 75., 12.],
       [85.,  6., 80., 14., 99., 12., 72., 14., 27., 20.]])

In [ ]:
print(mat.min())
print(mat.max())
print(mat.sum())

1.0
99.0
2124.0


0.0
100.0
2262.0


**Standard deviation of mat**

In [ ]:
mat.std()

30.531452634946806

28.664654192925475

**Sum of all columns of mat**

In [ ]:
mat.sum(axis=0)

array([347., 151., 254., 245., 232., 196., 237., 188., 214.,  60.])

array([347., 151., 254., 245., 232., 196., 237., 188., 214.,  60.])

**create array of dimension same as arr using arr.shape variable**

In [ ]:
arr = np.arange(100).reshape(4,5,5)
dim = arr.shape

In [ ]:
arr = np.arange(100).reshape(dim)

In [ ]:
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])